"""Generate the reference pages of the docs from the code.

    python scripts/generate_reference.py          # write them
    python scripts/generate_reference.py --check  # fail if they are stale

The reference cannot drift from the code because it is the code: every setting
from its dataclass and the comment above it, every method from its signature
and docstring, every CLI command from its definition, and the HTTP API from
OmniServe's own OpenAPI document. ``tests/test_reference_docs.py`` fails when
the committed pages differ from what this writes.
"""

from __future__ import annotations

import argparse
import ast
import inspect
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "reference"
NOTICE = "{/* Generated by scripts/generate_reference.py from the code. Do not edit by hand. */}"


# --- text ---------------------------------------------------------------------


def md(text: str) -> str:
    """Prose from a comment or docstring, safe in MDX: code spans kept, braces
    and angle brackets outside them escaped."""
    text = re.sub(r"``([^`]+)``", r"`\1`", text or "")
    parts = re.split(r"(`[^`]*`)", text)
    for i, part in enumerate(parts):
        if not part.startswith("`"):
            parts[i] = part.replace("{", "\\{").replace("}", "\\}").replace("<", "&lt;").replace(">", "&gt;")
    return "".join(parts).strip()


def code(value: str) -> str:
    """A value as an inline code span, in a table cell."""
    value = value.replace("|", "\\|")
    return f"`{value}`"


def first_paragraph(doc: str | None) -> str:
    doc = inspect.cleandoc(doc or "")
    return " ".join(doc.split("\n\n")[0].split()) if doc else ""


# --- settings -----------------------------------------------------------------


def _fields_with_comments(path: Path, class_name: str) -> list[dict[str, Any]]:
    """Each field of a dataclass with its type, declared default and the
    comment above it — or above the group of fields it belongs to."""
    source = path.read_text()
    lines = source.splitlines()
    tree = ast.parse(source)
    node = next(n for n in ast.walk(tree) if isinstance(n, ast.ClassDef) and n.name == class_name)
    fields, group_comment = [], None
    for stmt in node.body:
        if not (isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name)):
            continue
        comment, i = [], stmt.lineno - 2
        while i >= 0 and lines[i].strip().startswith("#"):
            comment.insert(0, lines[i].strip().lstrip("#").strip())
            i -= 1
        if comment:
            group_comment = comment
        elif lines[stmt.lineno - 2].strip() == "":
            group_comment = None
        text = " ".join(line for line in (comment or group_comment or []) if line)
        if not text:
            raise SystemExit(f"{class_name}.{stmt.target.id} has no comment explaining it")
        fields.append(
            {
                "name": stmt.target.id,
                "type": ast.get_source_segment(source, stmt.annotation),
                "declared": ast.get_source_segment(source, stmt.value) if stmt.value else None,
                "doc": text,
            }
        )
    return fields


def _default(instance: Any, field: dict[str, Any]) -> str:
    declared = field["declared"] or ""
    if "default_factory" in declared:
        value = getattr(instance, field["name"])
        return json.dumps(value, sort_keys=True, default=str) if not isinstance(value, str) else repr(value)
    return declared


def settings_page(title: str, description: str, intro: str, path: Path, class_name: str, instance: Any, skip: set[str] = frozenset()) -> str:
    rows, details = [], []
    for field in _fields_with_comments(path, class_name):
        if field["name"] in skip:
            continue
        default = _default(instance, field)
        if len(default) > 40 and default.startswith(("{", "[")):
            # A structured default is readable only laid out.
            details += [
                f"### `{field['name']}`",
                "",
                md(field["doc"]),
                "",
                "```json",
                json.dumps(json.loads(default), indent=2, sort_keys=True),
                "```",
                "",
            ]
            shown = "see below"
        else:
            shown = code(default)
        rows.append(f"| {code(field['name'])} | {code(field['type'])} | {shown} | {md(field['doc'])} |")
    return "\n".join(
        [
            "---",
            f"title: {title}",
            f"description: '{description}'",
            "icon: 'sliders'",
            "---",
            "",
            NOTICE,
            "",
            f"# {title}",
            "",
            intro,
            "",
            "| Setting | Type | Default | What it does |",
            "|---|---|---|---|",
            *rows,
            "",
            *(["## Defaults in full", "", *details] if details else []),
        ]
    )


# --- OmniCoreAgent ------------------------------------------------------------


def _args_section(doc: str) -> dict[str, str]:
    """The ``Args:`` entries of a Google-style docstring."""
    doc = inspect.cleandoc(doc or "")
    found, current = {}, None
    in_args = False
    for line in doc.splitlines():
        if line.strip() in ("Args:", "Arguments:", "Parameters:"):
            in_args = True
            continue
        if in_args and line.strip().endswith(":") and not line.startswith(" "):
            break
        match = re.match(r"\s+(\w+)(?: \([^)]*\))?:\s*(.*)", line) if in_args else None
        if match:
            current = match.group(1)
            found[current] = match.group(2)
        elif in_args and current and line.strip():
            found[current] += " " + line.strip()
    return found


def agent_page() -> str:
    from omnicoreagent import OmniCoreAgent

    init = inspect.signature(OmniCoreAgent.__init__)
    args = _args_section(OmniCoreAgent.__init__.__doc__)
    rows = []
    for name, parameter in init.parameters.items():
        if name == "self":
            continue
        default = "required" if parameter.default is inspect._empty else repr(parameter.default)
        rows.append(f"| {code(name)} | {code(default)} | {md(args.get(name, ''))} |")

    methods = []
    for name, function in sorted(inspect.getmembers(OmniCoreAgent, predicate=inspect.isfunction)):
        if name.startswith("_"):
            continue
        signature = str(inspect.signature(function)).replace("self, ", "").replace("(self)", "()")
        # Annotations are strings here (``from __future__ import annotations``).
        signature = re.sub(r"(: |-> )'([^']*)'", r"\1\2", signature)
        kind = "async " if inspect.iscoroutinefunction(function) else ""
        methods += [
            f"### `{name}`",
            "",
            "```python",
            f"{kind}def {name}{signature}: ...",
            "```",
            "",
            md(first_paragraph(function.__doc__)) or "_No description in the code yet._",
            "",
        ]
    return "\n".join(
        [
            "---",
            "title: OmniCoreAgent",
            "description: 'The agent: its constructor and every public method'",
            "icon: 'robot'",
            "---",
            "",
            NOTICE,
            "",
            "# OmniCoreAgent",
            "",
            "```python",
            "from omnicoreagent import OmniCoreAgent",
            "```",
            "",
            "## Constructor",
            "",
            "| Argument | Default | What it is |",
            "|---|---|---|",
            *rows,
            "",
            "`agent_config` takes the [agent settings](/docs/reference/agent-config), and",
            "`telemetry_config` the [telemetry settings](/docs/reference/telemetry-config).",
            "",
            "## Methods",
            "",
            *methods,
        ]
    )


# --- CLI ----------------------------------------------------------------------


def _options_table(command) -> list[str]:
    import click

    rows = []
    for param in command.params:
        if isinstance(param, click.Argument):
            names, kind = param.name.upper(), "argument"
        else:
            names = ", ".join(param.opts + param.secondary_opts)
            kind = "flag" if getattr(param, "is_flag", False) else (param.type.name if param.type else "")
            if isinstance(param.type, click.Choice):
                kind = " \\| ".join(param.type.choices)
        default = param.default
        unset = default in (None, (), [], False) or callable(default) or "Sentinel" in repr(default)
        if getattr(param, "required", False):
            shown = "required"
        else:
            shown = "" if unset else code(str(default))
        rows.append(f"| {code(names)} | {kind} | {shown} | {md(getattr(param, 'help', '') or '')} |")
    if not rows:
        return []
    return ["| Option | Takes | Default | What it does |", "|---|---|---|---|", *rows, ""]


def cli_page() -> str:
    from omnicoreagent.cli import cli as oca
    from omnicoreagent.cli.harbor_doctor import doctor_command
    from omnicoreagent.cli.harbor_results import results_command
    from omnicoreagent.serve.cli import cli as omniserve

    lines = [
        "---",
        "title: Command line",
        "description: 'Every omnicoreagent and omniserve command, and every flag'",
        "icon: 'terminal'",
        "---",
        "",
        NOTICE,
        "",
        "# Command line",
        "",
        "Two commands are installed: `omnicoreagent` (headless runs, and Harbor) and",
        "`omniserve` (the server, with `omnicoreagent[serve]`).",
        "",
    ]
    for name, command in sorted(oca.commands.items()):
        lines += [f"## `omnicoreagent {name}`", "", md(inspect.cleandoc(command.help or "")), ""]
        if name == "harbor":
            lines += [
                "Every other Harbor command passes through: `omnicoreagent harbor run`, `view`,",
                "`job resume`, `init` and the rest take Harbor's own flags",
                "([Harbor guide](/docs/how-to-guides/harbor)).",
                "",
            ]
            for sub_name, sub in (("doctor", doctor_command), ("results", results_command)):
                lines += [f"### `omnicoreagent harbor {sub_name}`", "", md(inspect.cleandoc(sub.help or "")), "", *_options_table(sub)]
        else:
            lines += _options_table(command)
    for name, command in sorted(omniserve.commands.items()):
        lines += [f"## `omniserve {name}`", "", md(inspect.cleandoc(command.help or "")), "", *_options_table(command)]
    return "\n".join(lines)


# --- HTTP API -----------------------------------------------------------------


def openapi_document() -> str:
    os.environ.setdefault("LLM_API_KEY", "sk-reference-generation-only-0000")
    from omnicoreagent import OmniCoreAgent
    from omnicoreagent.serve.app_factory import create_omniserve_app
    from omnicoreagent.serve.config import OmniServeConfig

    agent = OmniCoreAgent(
        name="agent",
        system_instruction="Reference generation.",
        model_config={"provider": "openai", "model": "gpt-5.6-terra"},
    )
    app = create_omniserve_app(
        agent=agent,
        config=OmniServeConfig(),
        title="OmniServe",
        description=(
            "The HTTP API of an agent served with `omniserve run --agent agent.py`: runs, "
            "approvals, budgets, background tasks, sessions and the evidence of every run."
        ),
    )
    spec = app.openapi()
    # The document describes the API, not one build of it.
    spec["info"]["version"] = "latest"
    spec["servers"] = [{"url": "http://localhost:8000", "description": "omniserve run, locally"}]
    return json.dumps(spec, indent=2, sort_keys=True) + "\n"


# --- all of it ----------------------------------------------------------------


def render_all() -> dict[Path, str]:
    from omnicoreagent.core.runtime.config import AgentConfig
    from omnicoreagent.core.telemetry.redaction import TelemetryConfig

    return {
        OUT / "omnicoreagent.mdx": agent_page(),
        OUT / "agent-config.mdx": settings_page(
            "Agent settings",
            "Every key agent_config takes, its default, and what it does",
            "Everything `OmniCoreAgent(agent_config={...})` takes. Each description is the "
            "comment above the setting in the code.",
            ROOT / "src/omnicoreagent/core/runtime/config.py",
            "AgentConfig",
            AgentConfig(agent_name="agent"),
            skip={"agent_name"},
        ),
        OUT / "telemetry-config.mdx": settings_page(
            "Telemetry settings",
            "Every key telemetry_config takes, its default, and what it does",
            "Everything `OmniCoreAgent(telemetry_config={...})` takes: what a trace records, where "
            "it is kept, and for how long. Each description is the comment above the setting in the code.",
            ROOT / "src/omnicoreagent/core/telemetry/redaction.py",
            "TelemetryConfig",
            TelemetryConfig(),
        ),
        OUT / "cli.mdx": cli_page(),
        OUT / "openapi.json": openapi_document(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if a page is stale")
    options = parser.parse_args()
    stale = []
    for path, content in render_all().items():
        if options.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("stale, run `python scripts/generate_reference.py`:", ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
