"""Generate the reference pages of the docs from the code.

    python scripts/generate_reference.py          # write them
    python scripts/generate_reference.py --check  # fail if they are stale

The reference cannot drift from the code because it is the code: every setting
from its dataclass and the comment above it, every method from its signature
and docstring, every CLI command from its definition, and the HTTP API from
OmniServe's own OpenAPI document. ``tests/test_reference_docs.py`` fails when
the committed pages differ from what this writes.
"""

from __future__ import annotations

import argparse
import ast
import inspect
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "reference"
NOTICE = "{/* Generated by scripts/generate_reference.py from the code. Do not edit by hand. */}"


# --- text ---------------------------------------------------------------------


def md(text: str) -> str:
    """Prose from a comment or docstring, safe in MDX: code spans kept, braces
    and angle brackets outside them escaped."""
    text = re.sub(r"``([^`]+)``", r"`\1`", text or "")
    parts = re.split(r"(`[^`]*`)", text)
    for i, part in enumerate(parts):
        if not part.startswith("`"):
            parts[i] = part.replace("{", "\\{").replace("}", "\\}").replace("<", "&lt;").replace(">", "&gt;")
    return "".join(parts).strip()


def code(value: str) -> str:
    """A value as an inline code span, in a table cell."""
    value = value.replace("|", "\\|")
    return f"`{value}`"


def first_paragraph(doc: str | None) -> str:
    doc = inspect.cleandoc(doc or "")
    return " ".join(doc.split("\n\n")[0].split()) if doc else ""


# --- settings -----------------------------------------------------------------


def _fields_with_comments(path: Path, class_name: str) -> list[dict[str, Any]]:
    """Each field of a dataclass with its type, declared default and the
    comment above it — or above the group of fields it belongs to."""
    source = path.read_text()
    lines = source.splitlines()
    tree = ast.parse(source)
    node = next(n for n in ast.walk(tree) if isinstance(n, ast.ClassDef) and n.name == class_name)
    fields, group_comment = [], None
    for stmt in node.body:
        if not (isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name)):
            continue
        comment, i = [], stmt.lineno - 2
        while i >= 0 and lines[i].strip().startswith("#"):
            comment.insert(0, lines[i].strip().lstrip("#").strip())
            i -= 1
        if comment:
            group_comment = comment
        elif lines[stmt.lineno - 2].strip() == "":
            group_comment = None
        text = " ".join(line for line in (comment or group_comment or []) if line)
        if not text:
            raise SystemExit(f"{class_name}.{stmt.target.id} has no comment explaining it")
        fields.append(
            {
                "name": stmt.target.id,
                "type": ast.get_source_segment(source, stmt.annotation),
                "declared": ast.get_source_segment(source, stmt.value) if stmt.value else None,
                "doc": text,
            }
        )
    return fields


def _default(instance: Any, field: dict[str, Any]) -> str:
    declared = field["declared"] or ""
    if "default_factory" in declared:
        value = getattr(instance, field["name"])
        return json.dumps(value, sort_keys=True, default=str) if not isinstance(value, str) else repr(value)
    return declared


def settings_page(title: str, description: str, intro: str, path: Path, class_name: str, instance: Any, skip: set[str] = frozenset()) -> str:
    rows, details = [], []
    for field in _fields_with_comments(path, class_name):
        if field["name"] in skip:
            continue
        default = _default(instance, field)
        if len(default) > 40 and default.startswith(("{", "[")):
            # A structured default is readable only laid out.
            details += [
                f"### `{field['name']}`",
                "",
                md(field["doc"]),
                "",
                "```json",
                json.dumps(json.loads(default), indent=2, sort_keys=True),
                "```",
                "",
            ]
            shown = "see below"
        else:
            shown = code(default)
        rows.append(f"| {code(field['name'])} | {code(field['type'])} | {shown} | {md(field['doc'])} |")
    return "\n".join(
        [
            "---",
            f"title: {title}",
            f"description: '{description}'",
            "icon: 'sliders'",
            "---",
            "",
            NOTICE,
            "",
            f"# {title}",
            "",
            intro,
            "",
            "| Setting | Type | Default | What it does |",
            "|---|---|---|---|",
            *rows,
            "",
            *(["## Defaults in full", "", *details] if details else []),
        ]
    )


# --- OmniCoreAgent ------------------------------------------------------------


def _args_section(doc: str) -> dict[str, str]:
    """The ``Args:`` entries of a Google-style docstring."""
    doc = inspect.cleandoc(doc or "")
    found, current = {}, None
    in_args = False
    for line in doc.splitlines():
        if line.strip() in ("Args:", "Arguments:", "Parameters:"):
            in_args = True
            continue
        if in_args and line.strip().endswith(":") and not line.startswith(" "):
            break
        match = re.match(r"\s+(\w+)(?: \([^)]*\))?:\s*(.*)", line) if in_args else None
        if match:
            current = match.group(1)
            found[current] = match.group(2)
        elif in_args and current and line.strip():
            found[current] += " " + line.strip()
    return found


def _methods(cls: Any) -> list[str]:
    """Every public method: its signature as Python, and its docstring's first paragraph."""
    lines: list[str] = []
    for name, function in sorted(inspect.getmembers(cls, predicate=inspect.isfunction)):
        if name.startswith("_"):
            continue
        signature = str(inspect.signature(function)).replace("self, ", "").replace("(self)", "()")
        # Annotations are strings here (``from __future__ import annotations``).
        signature = re.sub(r"(: |-> )'([^']*)'", r"\1\2", signature)
        kind = "async " if inspect.iscoroutinefunction(function) else ""
        lines += [
            f"### `{name}`",
            "",
            "```python",
            f"{kind}def {name}{signature}: ...",
            "```",
            "",
            md(first_paragraph(function.__doc__)) or "_No description in the code yet._",
            "",
        ]
    return lines


def background_page() -> str:
    from omnicoreagent import BackgroundAgentManager
    from omnicoreagent.background.models import (
        TERMINAL_RUN_STATUSES,
        WAITING_RUN_STATUSES,
        OverlapPolicy,
        RunStatus,
    )

    return "\n".join(
        [
            "---",
            "title: BackgroundAgentManager",
            "description: 'Background tasks and runs: every method, run status and overlap policy'",
            "icon: 'clock'",
            "---",
            "",
            NOTICE,
            "",
            "# BackgroundAgentManager",
            "",
            "```python",
            "from omnicoreagent import BackgroundAgentManager",
            "",
            "manager = BackgroundAgentManager()                    # tasks kept in memory",
            "manager = BackgroundAgentManager(task_store=\"sql\")   # SQLite, or DATABASE_URL; needs omnicoreagent[postgres]",
            "```",
            "",
            "The guide is [Background agents](/docs/core-concepts/background-agents).",
            "",
            "## Run statuses",
            "",
            "A run is `queued`, then `claimed` by a worker, `running`, and `retrying` between",
            "attempts. It **ends** in a terminal status, or **pauses** in a waiting one until",
            "`resume_run`; `run_now(wait=True)` and `wait_for_run` return at either.",
            "",
            "| Status | |",
            "|---|---|",
            *[
                f"| {code(status.value)} | "
                + ("ends" if status in TERMINAL_RUN_STATUSES else "waits" if status in WAITING_RUN_STATUSES else "active")
                + " |"
                for status in RunStatus
            ],
            "",
            "## Overlap policies",
            "",
            "What a task does when it is due while one of its runs is still active",
            "(`overlap_policy`; the default is `skip_if_running`):",
            "",
            "| Policy |",
            "|---|",
            *[f"| {code(policy.value)} |" for policy in OverlapPolicy],
            "",
            "## Methods",
            "",
            *_methods(BackgroundAgentManager),
        ]
    )


def agent_page() -> str:
    from omnicoreagent import OmniCoreAgent

    init = inspect.signature(OmniCoreAgent.__init__)
    args = _args_section(OmniCoreAgent.__init__.__doc__)
    rows = []
    for name, parameter in init.parameters.items():
        if name == "self":
            continue
        default = "required" if parameter.default is inspect._empty else repr(parameter.default)
        rows.append(f"| {code(name)} | {code(default)} | {md(args.get(name, ''))} |")

    methods = _methods(OmniCoreAgent)
    return "\n".join(
        [
            "---",
            "title: OmniCoreAgent",
            "description: 'The agent: its constructor and every public method'",
            "icon: 'robot'",
            "---",
            "",
            NOTICE,
            "",
            "# OmniCoreAgent",
            "",
            "```python",
            "from omnicoreagent import OmniCoreAgent",
            "```",
            "",
            "## Constructor",
            "",
            "| Argument | Default | What it is |",
            "|---|---|---|",
            *rows,
            "",
            "`agent_config` takes the [agent settings](/docs/reference/agent-config), and",
            "`telemetry_config` the [telemetry settings](/docs/reference/telemetry-config).",
            "",
            "## Methods",
            "",
            *methods,
        ]
    )


# --- Policy -------------------------------------------------------------------


def _compact(value: Any) -> str:
    """A target or conditions object as the dict a rule is written with."""
    if value is None:
        return ""
    data = value if isinstance(value, dict) else {
        key: getattr(value, key) for key in getattr(value, "__dataclass_fields__", {})
    }
    shown = {key: getattr(item, "value", item) for key, item in data.items() if item not in (None, [], {}, False)}
    return code(repr(shown)) if shown else ""


def policy_page() -> str:
    from omnicoreagent.governance import build_default_policy
    from omnicoreagent.governance.capabilities import CAPABILITIES
    from omnicoreagent.governance.models import PolicyProfile

    capability_rows = [f"| {code(name)} | {md(text)} |" for name, text in sorted(CAPABILITIES.items())]
    profiles = []
    for profile in PolicyProfile:
        policy = build_default_policy(profile.value)
        mode = getattr(policy.mode, "value", policy.mode)
        profiles += [f"### `{profile.value}`", "", f"Mode `{mode}`.", "", "| Effect | Rule | Capability | Target | Conditions |", "|---|---|---|---|---|"]
        for effect in ("deny", "ask", "allow"):
            for rule in getattr(policy.rules, effect):
                profiles.append(
                    f"| {effect} | {code(rule.rule_id)} | {code(rule.capability)} | "
                    f"{_compact(rule.target)} | {_compact(rule.conditions)} |"
                )
        profiles.append("")
    return "\n".join(
        [
            "---",
            "title: Policy",
            "description: 'Every capability, how a request is decided, how to write a rule, and what each built-in profile allows'",
            "icon: 'shield-halved'",
            "---",
            "",
            NOTICE,
            "",
            "# Policy",
            "",
            "Every action an agent takes is a **request** for a **capability**, with a",
            "**target** (the tool, the path, the host, the server). The policy decides each",
            "request: **allow** it, **deny** it, or **ask** a person. An ask pauses the run",
            "until someone decides ([durable runs](/docs/core-concepts/durable-runs)); the",
            "[security model](/docs/core-concepts/security-model) explains the design.",
            "",
            "## How a request is decided",
            "",
            "1. A **deny** rule that matches wins.",
            "2. Otherwise an **ask** rule that matches: a person decides. An ask outranks",
            "   an allow, so adding an allow rule to a profile does not lift that profile's",
            "   asks; remove the ask rule, or write your own policy.",
            "3. Otherwise an **allow** rule that matches.",
            "4. Otherwise the policy's **mode** decides: `permissive` allows,",
            "   `interactive` asks (reason `unknown_capability`), `strict` denies.",
            "",
            "A decision is recorded in the run's trace with its `effect` and `reason_code`",
            "(`matched_allow`, `matched_ask`, `matched_deny`, `unknown_capability`,",
            "`approved` when a person allowed an ask, and others).",
            "",
            "Two capabilities are decided when the agent connects, not during a run:",
            "`mcp.server.start` and `mcp.server.connect`. There is no run to pause then, so",
            "an ask on them fails the connection with `ApprovalRequiredError`; allow the",
            "servers you trust.",
            "",
            "The served agent's policy also decides what an operator asks of OmniServe's",
            "background API: `background.task.*` and `background.run.*`. A refusal there is",
            "an HTTP `403`.",
            "",
            "## Writing a rule",
            "",
            "```python",
            "from omnicoreagent.governance import PolicyEffect, PolicyRule, build_default_policy",
            "",
            "policy = build_default_policy(\"interactive-dev\")",
            "policy.rules.ask.append(",
            "    PolicyRule(",
            "        rule_id=\"ask_before_refunds\",",
            "        effect=PolicyEffect.ASK,",
            "        capability=\"tool.local.call\",",
            "        target={\"tool_name\": \"issue_refund\"},",
            "    )",
            ")",
            "agent_config = {\"governance_config\": {\"enabled\": True, \"policy\": policy}}",
            "```",
            "",
            "Or the whole policy as a dict:",
            "",
            "```python",
            "agent_config = {",
            "    \"governance_config\": {",
            "        \"enabled\": True,",
            "        \"policy\": {",
            "            \"name\": \"support-desk\",",
            "            \"mode\": \"strict\",  # anything no rule covers is denied",
            "            \"rules\": {",
            "                \"allow\": [{\"rule_id\": \"tools\", \"capability\": \"tool.local.call\"}],",
            "                \"ask\": [",
            "                    {",
            "                        \"rule_id\": \"refunds\",",
            "                        \"capability\": \"tool.local.call\",",
            "                        \"target\": {\"tool_name\": \"issue_refund\"},",
            "                    }",
            "                ],",
            "            },",
            "        },",
            "    }",
            "}",
            "```",
            "",
            "| Field | What it is |",
            "|---|---|",
            "| `rule_id` | Your name for the rule; it is recorded with every decision it makes. |",
            "| `effect` | `allow`, `ask` or `deny` (the list it is in, for a dict policy). |",
            "| `capability` | A capability below, or a glob: `workspace.files.*`, `network.http.*`, `*`. |",
            "| `target` | Optional. Any of `tool_name`, `mcp_server`, `path`, `host`, `resource`; each a glob the request's target must match. |",
            "| `conditions` | Optional. `risk_level` (list), `provider`, `execution_surface`, `exclude_execution_surface` (list), `exclude_capability` (list of globs), `mcp_server`, `method`, `host`. |",
            "| `constraints` | Optional. `approval_expires_seconds` (how long a person's decision stays valid), `sandbox_required`, `audit_required`. |",
            "",
            "## Capabilities",
            "",
            "| Capability | Allowing it lets the agent |",
            "|---|---|",
            *capability_rows,
            "",
            "## Built-in profiles",
            "",
            "Each profile below is `build_default_policy(name)`. Start from one and add",
            "rules, or write your own policy.",
            "",
            *profiles,
        ]
    )


# --- Budgets ------------------------------------------------------------------


def budgets_page() -> str:
    from omnicoreagent.core.budgets import (
        DEFAULT_ASSUMED_OUTPUT_TOKENS,
        METER_DESCRIPTIONS,
        METERS,
        WINDOW_DESCRIPTIONS,
        WINDOWS,
    )
    from omnicoreagent.governance.models import BUDGET_SCOPES, BudgetLimit

    limit_doc = inspect.getdoc(BudgetLimit) or ""
    return "\n".join(
        [
            "---",
            "title: Budgets",
            "description: 'Every meter, window and scope a budget can use, what happens when one runs out, and how a person tops it up'",
            "icon: 'wallet'",
            "---",
            "",
            NOTICE,
            "",
            "# Budgets",
            "",
            "Budgets are set in `governance_config[\"budgets\"]`, one list of limits per",
            "scope. Each limit caps one **meter** over one **window**.",
            "",
            "```python",
            "agent_config = {",
            "    \"governance_config\": {",
            "        \"enabled\": True,",
            "        \"profile\": \"interactive-dev\",",
            "        \"budgets\": {",
            "            \"application_id\": \"support-desk\",",
            "            \"application\": [{\"meter\": \"model_cost_usd\", \"limit\": 20.0, \"window\": \"day\"}],",
            "            \"request\": [",
            "                {\"meter\": \"model_cost_usd\", \"limit\": 0.50},",
            "                {\"meter\": \"tool_calls\", \"limit\": 40, \"on_exhausted\": \"terminate\"},",
            "            ],",
            "        },",
            "    }",
            "}",
            "```",
            "",
            "## Scopes",
            "",
            "| Scope | Counts |",
            "|---|---|",
            "| `request` | One run, from `run()` to its end, resumes included. The same limit applies to every run of the agent. |",
            "| `session` | Every run with the same `session_id`. |",
            "| `agent` | Every run of this agent. |",
            "| `application` | Every agent that names the same `application_id` (required for this scope). |",
            "",
            f"Scopes: {', '.join(code(scope) for scope in BUDGET_SCOPES)}.",
            "",
            "## Meters",
            "",
            "| Meter | Counts |",
            "|---|---|",
            *[f"| {code(meter)} | {md(METER_DESCRIPTIONS[meter])} |" for meter in METERS],
            "",
            f"A model call's price is held before the call: the input it counts, and the output at `model_config[\"max_tokens\"]`, or {DEFAULT_ASSUMED_OUTPUT_TOKENS} tokens (sent to the provider as the call's ceiling) when none is set.",
            "",
            "## Windows",
            "",
            "| Window | Resets |",
            "|---|---|",
            *[f"| {code(window)} | {md(WINDOW_DESCRIPTIONS[window])} |" for window in WINDOWS],
            "",
            "## A limit",
            "",
            "| Field | Default | |",
            "|---|---|---|",
            "| `meter` | required | One of the meters above. |",
            "| `limit` | required | Greater than zero, in the meter's unit. |",
            "| `window` | `\"total\"` | One of the windows above. |",
            "| `warn_at` | `0.8` | The fraction of the limit that records a warning in the trace. |",
            "| `on_exhausted` | `\"pause\"` | `pause`: the run waits for a person (`awaiting_budget`). `terminate`: the run ends. |",
            "",
            md(limit_doc.split("\n\n")[0]),
            "",
            "## When a budget runs out",
            "",
            "A run that would go over a `pause` limit stops **before** the call and returns",
            "`status: \"awaiting_budget\"` with `budget_request`: the budget, what is spent, what",
            "the call needs, and the shortfall. Then:",
            "",
            "- `await agent.grant_budget(run_id, approver=..., amount=...)` adds to that budget",
            "  (without `amount`, just the shortfall of the call that stopped), recorded with",
            "  the approver's name; then `await agent.resume(run_id)`.",
            "- `await agent.deny_budget(run_id, approver=...)` ends the run instead.",
            "- `await agent.budget_status(run_id)` shows each budget's `limit`, `granted`,",
            "  `spent`, `reserved` and `remaining`.",
            "",
            "Over HTTP: `GET /runs/{run_id}/budget` (the budgets and the run's `requests`) and",
            "`POST /runs/{run_id}/budget`. The design is in",
            "[durable runs](/docs/core-concepts/durable-runs).",
        ]
    )


# --- CLI ----------------------------------------------------------------------


def _options_table(command) -> list[str]:
    import click

    rows = []
    for param in command.params:
        if isinstance(param, click.Argument):
            names, kind = param.name.upper(), "argument"
        else:
            names = ", ".join(param.opts + param.secondary_opts)
            kind = "flag" if getattr(param, "is_flag", False) else (param.type.name if param.type else "")
            if isinstance(param.type, click.Choice):
                kind = " \\| ".join(param.type.choices)
        default = param.default
        unset = default in (None, (), [], False) or callable(default) or "Sentinel" in repr(default)
        if getattr(param, "required", False):
            shown = "required"
        else:
            shown = "" if unset else code(str(default))
        rows.append(f"| {code(names)} | {kind} | {shown} | {md(getattr(param, 'help', '') or '')} |")
    if not rows:
        return []
    return ["| Option | Takes | Default | What it does |", "|---|---|---|---|", *rows, ""]


def cli_page() -> str:
    from omnicoreagent.cli import cli as oca
    from omnicoreagent.cli.harbor_doctor import doctor_command
    from omnicoreagent.cli.harbor_results import results_command
    from omnicoreagent.serve.cli import cli as omniserve

    lines = [
        "---",
        "title: Command line",
        "description: 'Every omnicoreagent and omniserve command, and every flag'",
        "icon: 'terminal'",
        "---",
        "",
        NOTICE,
        "",
        "# Command line",
        "",
        "Two commands are installed: `omnicoreagent` (headless runs, and Harbor) and",
        "`omniserve` (the server, with `omnicoreagent[serve]`).",
        "",
    ]
    for name, command in sorted(oca.commands.items()):
        lines += [f"## `omnicoreagent {name}`", "", md(inspect.cleandoc(command.help or "")), ""]
        if name == "harbor":
            lines += [
                "Every other Harbor command passes through: `omnicoreagent harbor run`, `view`,",
                "`job resume`, `init` and the rest take Harbor's own flags",
                "([Harbor guide](/docs/how-to-guides/harbor)).",
                "",
            ]
            for sub_name, sub in (("doctor", doctor_command), ("results", results_command)):
                lines += [f"### `omnicoreagent harbor {sub_name}`", "", md(inspect.cleandoc(sub.help or "")), "", *_options_table(sub)]
        else:
            lines += _options_table(command)
    for name, command in sorted(omniserve.commands.items()):
        lines += [f"## `omniserve {name}`", "", md(inspect.cleandoc(command.help or "")), "", *_options_table(command)]
    return "\n".join(lines)


# --- HTTP API -----------------------------------------------------------------


def openapi_document() -> str:
    os.environ.setdefault("LLM_API_KEY", "sk-reference-generation-only-0000")
    from omnicoreagent import OmniCoreAgent
    from omnicoreagent.serve.app_factory import create_omniserve_app
    from omnicoreagent.serve.config import OmniServeConfig

    agent = OmniCoreAgent(
        name="agent",
        system_instruction="Reference generation.",
        model_config={"provider": "openai", "model": "gpt-5.6-terra"},
    )
    app = create_omniserve_app(
        agent=agent,
        config=OmniServeConfig(),
        title="OmniServe",
        description=(
            "The HTTP API of an agent served with `omniserve run --agent agent.py`: runs, "
            "approvals, budgets, background tasks, sessions and the evidence of every run."
        ),
    )
    spec = app.openapi()
    # The document describes the API, not one build of it.
    spec["info"]["version"] = "latest"
    spec["servers"] = [{"url": "http://localhost:8000", "description": "omniserve run, locally"}]
    return json.dumps(spec, indent=2, sort_keys=True) + "\n"


# --- all of it ----------------------------------------------------------------


def render_all() -> dict[Path, str]:
    from omnicoreagent.core.runtime.config import AgentConfig
    from omnicoreagent.core.telemetry.redaction import TelemetryConfig

    return {
        OUT / "omnicoreagent.mdx": agent_page(),
        OUT / "agent-config.mdx": settings_page(
            "Agent settings",
            "Every key agent_config takes, its default, and what it does",
            "Everything `OmniCoreAgent(agent_config={...})` takes. Each description is the "
            "comment above the setting in the code.",
            ROOT / "src/omnicoreagent/core/runtime/config.py",
            "AgentConfig",
            AgentConfig(agent_name="agent"),
            skip={"agent_name"},
        ),
        OUT / "telemetry-config.mdx": settings_page(
            "Telemetry settings",
            "Every key telemetry_config takes, its default, and what it does",
            "Everything `OmniCoreAgent(telemetry_config={...})` takes: what a trace records, where "
            "it is kept, and for how long. Each description is the comment above the setting in the code.",
            ROOT / "src/omnicoreagent/core/telemetry/redaction.py",
            "TelemetryConfig",
            TelemetryConfig(),
        ),
        OUT / "policy.mdx": policy_page(),
        OUT / "background.mdx": background_page(),
        OUT / "budgets.mdx": budgets_page(),
        OUT / "cli.mdx": cli_page(),
        OUT / "openapi.json": openapi_document(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if a page is stale")
    options = parser.parse_args()
    stale = []
    for path, content in render_all().items():
        if options.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("stale, run `python scripts/generate_reference.py`:", ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
