"""Durable background execution for OmniCoreAgent."""

from omnicoreagent.background.errors import (
    AgentAlreadyRegisteredError,
    AgentNotFoundError,
    BackgroundAgentError,
    InvalidScheduleError,
    InvalidTaskStoreError,
    RunCancelledError,
    RunExecutionError,
    RunLeaseError,
    RunNotFoundError,
    RunTimeoutError,
    TaskAlreadyRegisteredError,
    TaskNotFoundError,
    TaskStoreError,
)
from omnicoreagent.background.manager import BackgroundAgentManager
from omnicoreagent.background.models import (
    BackgroundAgentSpec,
    BackgroundAttempt,
    BackgroundRun,
    BackgroundScheduleState,
    BackgroundTaskSpec,
    OverlapPolicy,
    RetryPolicy,
    RunStatus,
    ScheduleSpec,
    SessionPolicy,
    TaskStoreBackend,
    TaskStoreConfig,
    WorkspacePolicy,
)
from omnicoreagent.background.store import (
    AbstractTaskStore,
    InMemoryTaskStore,
    SqlTaskStore,
    TaskStoreRouter,
)

__all__ = [
    "AbstractTaskStore",
    "AgentAlreadyRegisteredError",
    "AgentNotFoundError",
    "BackgroundAgentError",
    "BackgroundAgentManager",
    "BackgroundAgentSpec",
    "BackgroundAttempt",
    "BackgroundRun",
    "BackgroundScheduleState",
    "BackgroundTaskSpec",
    "InMemoryTaskStore",
    "InvalidScheduleError",
    "InvalidTaskStoreError",
    "OverlapPolicy",
    "RetryPolicy",
    "RunCancelledError",
    "RunExecutionError",
    "RunLeaseError",
    "RunNotFoundError",
    "RunStatus",
    "RunTimeoutError",
    "ScheduleSpec",
    "SessionPolicy",
    "SqlTaskStore",
    "TaskAlreadyRegisteredError",
    "TaskNotFoundError",
    "TaskStoreBackend",
    "TaskStoreConfig",
    "TaskStoreError",
    "TaskStoreRouter",
    "WorkspacePolicy",
]
